<?php

namespace Webkul\Admin\Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AttributeSeeder extends Seeder
{

    public function run()
    {
        DB::table('attributes')->delete();

        $now = Carbon::now();

        DB::table('attributes')->insert([
            [
                'id'                  => '1',
                'code'                => 'title',
                'name'                => 'Title',
                'type'                => 'text',
                'entity_type'         => 'leads',
                'validation'          => NULL,
                'sort_order'          => '1',
                'is_required'         => '1',
                'is_unique'           => '0',
                'quick_add'           => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '2',
                'code'                => 'description',
                'name'                => 'Description',
                'type'                => 'textarea',
                'entity_type'         => 'leads',
                'validation'          => NULL,
                'sort_order'          => '2',
                'is_required'         => '0',
                'is_unique'           => '0',
                'quick_add'           => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '3',
                'code'                => 'lead_value',
                'name'                => 'Lead Value',
                'type'                => 'price',
                'entity_type'         => 'leads',
                'validation'          => NULL,
                'sort_order'          => '3',
                'is_required'         => '1',
                'is_unique'           => '0',
                'quick_add'           => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '4',
                'code'                => 'source',
                'name'                => 'Source',
                'type'                => 'text',
                'entity_type'         => 'leads',
                'validation'          => NULL,
                'sort_order'          => '4',
                'is_required'         => '1',
                'is_unique'           => '0',
                'quick_add'           => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '5',
                'code'                => 'type',
                'name'                => 'Type',
                'type'                => 'text',
                'entity_type'         => 'leads',
                'validation'          => NULL,
                'sort_order'          => '5',
                'is_required'         => '1',
                'is_unique'           => '0',
                'quick_add'           => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '6',
                'code'                => 'tags',
                'name'                => 'Tags',
                'type'                => 'lookup',
                'entity_type'         => 'leads',
                'validation'          => NULL,
                'sort_order'          => '6',
                'is_required'         => '0',
                'is_unique'           => '0',
                'quick_add'           => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '7',
                'code'                => 'stage',
                'name'                => 'Stage',
                'type'                => 'lookup',
                'entity_type'         => 'leads',
                'validation'          => NULL,
                'sort_order'          => '7',
                'is_required'         => '0',
                'is_unique'           => '0',
                'quick_add'           => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '8',
                'code'                => 'first_name',
                'name'                => 'First Name',
                'type'                => 'text',
                'entity_type'         => 'persons',
                'validation'          => NULL,
                'sort_order'          => '1',
                'is_required'         => '1',
                'is_unique'           => '0',
                'quick_add'           => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '9',
                'code'                => 'last_name',
                'name'                => 'Last Name',
                'type'                => 'text',
                'entity_type'         => 'persons',
                'validation'          => NULL,
                'sort_order'          => '2',
                'is_required'         => '1',
                'is_unique'           => '0',
                'quick_add'           => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '10',
                'code'                => 'emails',
                'name'                => 'Emails',
                'type'                => 'email',
                'entity_type'         => 'persons',
                'validation'          => NULL,
                'sort_order'          => '3',
                'is_required'         => '1',
                'is_unique'           => '1',
                'quick_add'           => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '11',
                'code'                => 'contact_numbers',
                'name'                => 'Contact Numbers',
                'type'                => 'phone',
                'entity_type'         => 'persons',
                'validation'          => 'numeric',
                'sort_order'          => '4',
                'is_required'         => '0',
                'is_unique'           => '0',
                'quick_add'           => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '12',
                'code'                => 'organization',
                'name'                => 'Organization',
                'type'                => 'lookup',
                'entity_type'         => 'persons',
                'validation'          => NULL,
                'sort_order'          => '6',
                'is_required'         => '1',
                'is_unique'           => '0',
                'quick_add'           => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '13',
                'code'                => 'name',
                'name'                => 'Name',
                'type'                => 'text',
                'entity_type'         => 'organizations',
                'validation'          => NULL,
                'sort_order'          => '1',
                'is_required'         => '1',
                'is_unique'           => '0',
                'quick_add'           => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '14',
                'code'                => 'address',
                'name'                => 'Address',
                'type'                => 'address',
                'entity_type'         => 'organizations',
                'validation'          => NULL,
                'sort_order'          => '2',
                'is_required'         => '1',
                'is_unique'           => '0',
                'quick_add'           => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '15',
                'code'                => 'name',
                'name'                => 'Name',
                'type'                => 'text',
                'entity_type'         => 'products',
                'validation'          => NULL,
                'sort_order'          => '1',
                'is_required'         => '1',
                'is_unique'           => '0',
                'quick_add'           => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '16',
                'code'                => 'description',
                'name'                => 'Description',
                'type'                => 'textarea',
                'entity_type'         => 'products',
                'validation'          => NULL,
                'sort_order'          => '1',
                'is_required'         => '0',
                'is_unique'           => '0',
                'quick_add'           => '0',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '17',
                'code'                => 'sku',
                'name'                => 'SKU',
                'type'                => 'text',
                'entity_type'         => 'products',
                'validation'          => NULL,
                'sort_order'          => '2',
                'is_required'         => '1',
                'is_unique'           => '1',
                'quick_add'           => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '18',
                'code'                => 'quantity',
                'name'                => 'Quantity',
                'type'                => 'text',
                'entity_type'         => 'products',
                'validation'          => 'numeric',
                'sort_order'          => '2',
                'is_required'         => '1',
                'is_unique'           => '0',
                'quick_add'           => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '19',
                'code'                => 'price',
                'name'                => 'Price',
                'type'                => 'text',
                'entity_type'         => 'products',
                'validation'          => 'decimal',
                'sort_order'          => '3',
                'is_required'         => '1',
                'is_unique'           => '0',
                'quick_add'           => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ]
        ]);
    }
}