server {
  listen 80 default_server;
  index index.php index.html;
  root /var/www/app/public;
  error_log  /var/log/nginx/error.log;
  access_log /var/log/nginx/access.log;  
  
  client_max_body_size 256M;
  
  location ~ \.php$ {
    disable_symlinks off;
    try_files $uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass app:9000;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_hide_header X-Powered-By;
  }
  
  location / {
    disable_symlinks off;
    try_files $uri $uri/ /index.php?$query_string;
  }

  location ~ /\.ht {
    deny all;
  }
}