<x-admin::form.control-group.control
    type="inline"
    :name="$attribute->name"
    :value="$value"
    rules="required|decimal:4"
    position="left"
    :label="$attribute->name"
    ::errors="errors"
    :placeholder="$attribute->name"
    :url="$url"
/>